apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - image: ghcr.io/munhunger/timestat/kit:{{ .Values.version }}
          ports:
            - containerPort: 3000
          env:
            - name: TARGET
              value: 'World'
